version: '3'

services:
  app:
    container_name: node
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app
    tty: true
    depends_on: 
      - db    

  db:
    container_name: db
    image: mysql:5.7             
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=FullCycleDB
      - MYSQL_ROOT_PASSWORD=password      

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app