services:
app:
  build:
    context: ./app
    dockerfile: Dockerfile
  restart: always
  ports:
    - "3000:3000"
  volumes:
    - ./app:/app
  depends_on:
    - db

db:
  image: mysql:5.7
  restart: always
  volumes:
    - ./db:/var/lib/mysql
    - ./db/init:/docker-entrypoint-initdb.d

nginx:
  build:
    context: ./nginx
    dockerfile: Dockerfile
  restart: always
  ports:
    - "8080:80"
  volumes:
    - ./nginx:/etc/nginx/conf.d
  depends_on:
    - app
    - db