version: '3'

services:

  app:
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    container_name: db
    image: mysql:5.7             
    command: --innodb-use-native-aio=0    
    volumes:
      - ./db:/usr/src/db
    tty: true
    environment: 
      - MYSQL_DATABASE=FullCycleDB
      - MYSQL_ROOT_PASSWORD=password      

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app